// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://remugtgbjkrxuegbiguq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlbXVndGdiamtyeHVlZ2JpZ3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwOTkwNDQsImV4cCI6MjA3ODY3NTA0NH0.BPpJ3zRzluIWyBQR1YkFTG2V0IGJihIhRS9TOm0My7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  functions: {
    url: SUPABASE_URL.replace('.supabase.co', '.functions.supabase.co'),
  }
});
